### ISSUE TITLE
`flyway: line 51: /home/runner/.jabba/jdk/adopt@1.11.0-11/bin/java: No such file or directory`

### ISSUE THREAD

**Issue by ccantarero91** [joshuaavalon/flyway-action#7]
Trying to use Flyway I am facing the following error:
![image](https://user-images.githubusercontent.com/26185566/195899559-7218a8bb-84d0-4bfe-9b9a-5438e9d83b56.png)
Is it something I am not configuring right?
Thanks

**Comment by joshuaavalon** [comment]
Did you set `JAVA_HOME` in your configuration? From the image above, I saw you set `JAVA_HOME` but the directory does not exist.

**Comment by ccantarero91** [comment]
Yes, you are right!
Thanks
